version: '3'
services:
  mysql:
    build: ./mysql
    container_name: mysql
    restart: always
    env_file: .env
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d

  redis:
    build: ./redis
    container_name: redis
    restart: always
    env_file: .env
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data"

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    env_file: .env
    ports:
      - "8080:80"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/html:/usr/share/nginx/html